language: julia
os:
  - linux
#  - osx
julia:
  - 0.4
 # - 0.5
 # - nightly
notifications:
  email: false
#script: # use the default script which is the same as the following
#  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
#  - julia --check-bounds=yes -e 'Pkg.clone(pwd()); Pkg.build("Smile");  Pkg.test("Smile"; coverage=true)'
after_success:
  - julia -e 'cd(Pkg.dir("Smile")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
